server:
  port: 7878
spring:
  data:
    mongodb:
      host: 10.222.22.156
      port: 27017
      username: officesmart_admin
      password: officesmart_admin
      database: officesmart

logging:
  config: classpath:logback-spring-dev.xml